### ISSUE TITLE
 official_devices: LG V30

### ISSUE THREAD

**Issue by FengDoge** [exthmui/official_devices#1]
https://github.com/FengDoge/android_device_lge_h930.git
https://github.com/FengDoge/android_device_lge_joan-common.git
https://github.com/FengDoge/android_kernel_lge_msm8998.git
https://github.com/FengDoge/android_vendor_lge_joan-common.git
https://github.com/FengDoge/android_vendor_lge_h930.git
https://github.com/FengDoge/android_device_lge_common.git
https://github.com/FengDoge/android_hardware_lge.git

**Comment by ghost** [comment]
LG V30已经有官方维护者，抱歉。
