### ISSUE TITLE
official_devices: Motorola Z2 Force

### ISSUE THREAD

**Issue by FengDoge** [exthmui/official_devices#2]
https://github.com/FengDoge/android_device_motorola_nash.git
https://github.com/FengDoge/android_kernel_motorola_msm8998.git
https://github.com/FengDoge/android_vendor_motorola_nash.git

**Comment by ghost** [comment]
已经收到了您的加入请求，但请不要把OFFICIAL申请放在github issues上面。
请加入我们的QQ群组，来申请任何的OFFICIAL设备：776741012 (直接加入 我会通过的)
